# Generated by Django 3.0.3 on 2020-03-04 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='p_name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료여부')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='완료일')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_board.ProjectCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_todo_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='todo_list',
        ),
    ]
